import 'dart:math';

import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:untitled/screens/ProductList.dart';
import 'package:modal_progress_hud/modal_progress_hud.dart';
import 'package:http/http.dart' as http;

String PrivacyPolicy = "http://app.snvschool.org/privacy_policy.html";
String AboutUs = "http://app.snvschool.org/about_us.html";
String ContactUs = "http://app.snvschool.org/contact_us.html";
String basePath = "http://app.snvschool.org/" + "SchoolWS.svc/";
String RegisterDevice = basePath + "RegisterDevice";
String ValidateToken = basePath + "ValidateToken";
String Login = basePath + "Login";
String SendLoginDetails = basePath + "SendLoginDetails";
String GetNotification = basePath + "GetNotification";
String GetHomework = basePath + "GetHomeworkReport";
String GetMaterial = basePath + "GetMaterial";
String GetAttendanceReport = basePath + "GetAttendanceReport";
String GetNotice = basePath + "GetNotice";
String GetAllSubjects = basePath + "GetSubject";
String GetChapter = basePath + "GetChapter";
String GetAllBranch = basePath + "GetAllBranch";
String ChangePassword = basePath + "ChangePassword";
String GetStudentProfile = basePath + "GetStudentProfile";
String AddQuery = basePath + "AddQuery";
String AddLeaveRequest = basePath + "AddLeaveRequest";
String GetStudentRemarks = basePath + "GetStudentRemarks";
String GetFoodMenu = basePath + "GetFoodMenu";
String GetSchedule = basePath + "GetSchedule";
String GetDailySession = basePath + "GetDailySession";
String GetDailyTest = basePath + "GetDailyTest";
String GetAllStandard = basePath + "GetAllStandard";
String GetChapters = basePath + "GetChapters";
String GetAllDivisions = basePath + "GetAllDivisions";
String AddVehicleLocation = basePath + "AddVehicleLocation";
String GetBusDetails = basePath + "GetBusDetails";
String AddSecondaryUser = basePath + "AddSecondaryUser";
String GetSecondaryUser = basePath + "GetSecondaryUser";
String GetEvents = basePath + "GetEvents";
String GetEventDetail = basePath + "GetEventDetail";
String UpdateFcm = basePath + "UpdateFcm";
